<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>NovinQuiz</RootNamespace>
		<AssemblyName>Ns.$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\NovinQuiz.MongoDB\NovinQuiz.MongoDB.csproj" />
		<ProjectReference Include="..\NovinQuiz.TestBase\NovinQuiz.TestBase.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
		<PackageReference Include="EphemeralMongo.Core" Version="1.1.0" />
		<PackageReference Include="EphemeralMongo6.runtime.linux-x64" Version="1.1.0" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
		<PackageReference Include="EphemeralMongo6.runtime.osx-x64" Version="1.1.0" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
		<PackageReference Include="EphemeralMongo6.runtime.win-x64" Version="1.1.0" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
	</ItemGroup>

</Project>
