<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>NovinQuiz</RootNamespace>
		<AssemblyName>Ns.$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\NovinQuiz.Application\NovinQuiz.Application.csproj" />
		<ProjectReference Include="..\NovinQuiz.Domain.Tests\NovinQuiz.Domain.Tests.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
	</ItemGroup>

</Project>
